service: aws-lambda

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/aws-lambda.zip

functions:
  smartrakLambda:
    handler: com.javaworld.awslambda.smarttrack.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /message/getVoltage
          method: POST
    timeout: 30