package com.javaworld.awslambda.smarttrack.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

/**
 * Created by anil.saladi on 9/26/2019.
 */
@DynamoDBTable(tableName = "power")
public class TTDPowerSupply implements Serializable {
    private static final long serialVersionUID = -3534650012619938612L;

    private String id;
    private String deviceId;
    private String deviceName;
    private String timestamp;
    private String ipAddress;
    private String power;
    private String energy;

    public TTDPowerSupply(String id, String deviceId, String deviceName, String timestamp, String ipAddress, String power, String energy) {
        this.id = id;
        this.deviceId = deviceId;
        this.deviceName = deviceName;
        this.timestamp = timestamp;
        this.ipAddress = ipAddress;
        this.power = power;
        this.energy = energy;
    }

    public TTDPowerSupply() {
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "deviceId")
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @DynamoDBAttribute(attributeName = "deviceName")
    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    @DynamoDBAttribute(attributeName = "timestamp")
    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @DynamoDBAttribute(attributeName = "power")
    public String getPower() {
        return power;
    }

    public void setPower(String power) {
        this.power = power;
    }

    @DynamoDBAttribute(attributeName = "energy")
    public String getEnergy() {
        return energy;
    }

    public void setEnergy(String energy) {
        this.energy = energy;
    }

    @DynamoDBAttribute(attributeName = "ipAddress")
    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @Override
    public String toString() {
        return "{" +
                "id:'" + id + '\'' +
                "deviceId:'" + deviceId + '\'' +
                ", deviceName:'" + deviceName + '\'' +
                ", timestamp:'" + timestamp + '\'' +
                ", ipAddress:'" + ipAddress + '\'' +
                ", power:'" + power + '\'' +
                ", energy:'" + energy + '\'' +
                '}';
    }
}
